# -*- coding: utf-8 -*-
# Auto-generated by Stone, do not modify.
# @generated
# flake8: noqa
# pylint: skip-file

from typing import (
    Callable,
    Optional,
    Text,
    Type,
    TypeVar,
)
from stone.backends.python_rsrc import stone_base as bb  # type: ignore
from stone.backends.python_rsrc import stone_validators as bv  # type: ignore

T = TypeVar('T', bound=bb.AnnotationType)
U = TypeVar('U')

class EchoArg(bb.Struct):
    def __init__(self,
                 query: Optional[Text] = ...) -> None: ...
    query: bb.Attribute[Text] = ...
    def _process_custom_annotations(
        self,
        annotation_type: Type[T],
        field_path: Text,
        processor: Callable[[T, U], U],
    ) -> None: ...

EchoArg_validator: bv.Validator = ...

class EchoResult(bb.Struct):
    def __init__(self,
                 result: Optional[Text] = ...) -> None: ...
    result: bb.Attribute[Text] = ...
    def _process_custom_annotations(
        self,
        annotation_type: Type[T],
        field_path: Text,
        processor: Callable[[T, U], U],
    ) -> None: ...

EchoResult_validator: bv.Validator = ...

app: bb.Route = ...
user: bb.Route = ...

