# -*- coding: utf-8 -*-
# Auto-generated by Stone, do not modify.
# @generated
# flake8: noqa
# pylint: skip-file

from typing import (
    Callable,
    Text,
    Type,
    TypeVar,
)
from stone.backends.python_rsrc import stone_base as bb  # type: ignore
from stone.backends.python_rsrc import stone_validators as bv  # type: ignore

T = TypeVar('T', bound=bb.AnnotationType)
U = TypeVar('U')

class AccountType(bb.Union):
    basic: AccountType = ...
    pro: AccountType = ...
    business: AccountType = ...

    def is_basic(self) -> bool: ...

    def is_pro(self) -> bool: ...

    def is_business(self) -> bool: ...

    def _process_custom_annotations(
        self,
        annotation_type: Type[T],
        field_path: Text,
        processor: Callable[[T, U], U],
    ) -> None: ...

AccountType_validator: bv.Validator = ...

AccountId_validator: bv.Validator = ...
